ignore_colors = [
 [0, 0, 0, 0],
 # [0, 0, 0, 255], # filter all black
]

# priority: higher number = higher chance of being placed
# r/placeDE overlay target: https://place.army/overlay_target.png
# r/ukPlace overlay target: https://placeuk.g3v.co.uk/template/ukplace

[versions]
"browser" = 20
"python" = 3
"nodejs" = 1

[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10

# region right side

[[structure]]
name = "flaguk"
file = "bonjwa/uk_flag_pixelart.png"
startx = 666
starty = 170
priority = 10

[[structure]]
name = "bonjwa-logo29"
file = "bonjwa/Bonjwa_Logo_29x29.png"
startx = 782
starty = 134
priority = 10

[[structure]]
name = "bonjwa-matteo-marius"
file = "bonjwa/Matteo-Marius-NeuerAlsNeu.png"
startx = 703
starty = 115
priority = 5

[[structure]]
name = "prinz"
file = "bonjwa/prinz3.png"
startx = 666
starty = 131
priority = 1

[[structure]]
name = "bonjwa-peepo2"
file = "bonjwa/peepo-1px-breiter.png"
startx = 688
starty = 132
priority = 1

[[structure]]
name = "kekluckeye"
file = "bonjwa/auge.png"
startx = 710
starty = 156
priority = 1

[[structure]]
name = "FlagArmenia"
file = "bonjwa/armenia_flag.png"
startx = 666
starty = 157
priority = 1

[[structure]]
name = "HeartArmenia"
file = "bonjwa/heart_bonjwa_armenia.png"
startx = 698
starty = 154
priority = 1

[[structure]]
name = "HeartUK"
file = "bonjwa/Herz.png"
startx = 781
starty = 167
priority = 2

[[structure]]
name = "HeartDE"
file = "bonjwa/deheart.png"
startx = 820
starty = 134
priority = 2

[[structure]]
name = "touri"
file = "bonjwa/Touri_AndiDesign_11x14_Twitter_Rosa.png"
startx = 810
starty = 155
priority = 10

# endregion

# region left side

[[structure]]
name = "helm"
file = "bonjwa/helm.png"
startx = 215
starty = 172
priority = 2

#[[structure]]
#name = "hugo"
#file = "bonjwa/hugo.png"
#startx = 301
#starty = 172
#priority = 3

[[structure]]
name = "bonjwa-rad"
file = "bonjwa/BonjwaRad.png"
startx = 273
starty = 134
priority = 10

[[structure]]
name = "gans"
file = "bonjwa/Gans.png"
startx = 215
starty = 145
priority = 3

[[structure]]
name = "pyramid"
file = "bonjwa/pyramid.png"
startx = 193
starty = 140
priority = 3

[[structure]]
name = "sukiandfriends"
file = "bonjwa/sukiandfriends2.png"
startx = 226
starty = 130
priority = 2

[[structure]]
name = "leaf"
file = "bonjwa/acleaf.png"
startx = 269
starty = 132
priority = 2

[[structure]]
name = "phunk"
file = "bonjwa/phunk.png"
startx = 302
starty = 135
priority = 2

[[structure]]
name = "schagges"
file = "bonjwa/schagges.png"
startx = 289
starty = 134
priority = 2

# endregion

# region misc

[[structure]]
name = "free-iran-flagge"
file = "bonjwa/Free_Iran_Flagge.png"
startx = 1555
starty = 381
priority = 1

[[structure]]
name = "suun"
file = "bonjwa/suun.png"
startx = 179
starty = 903
priority = 1

# endregion
