ignore_colors = [
 [0, 0, 0, 0],
 # [0, 0, 0, 255], # filter all black
]

# priority: higher number = higher chance of being placed
# r/placeDE overlay target: https://place.army/overlay_target.png
# r/ukPlace overlay target: https://placeuk.g3v.co.uk/template/ukplace

[versions]
"browser" = 20
"python" = 3
"nodejs" = 1

[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10

# region right side

[[structure]]
name = "flaguk"
file = "bonjwa/uk_flag_pixelart.png"
startx = 666
starty = 670
priority = 10

[[structure]]
name = "bonjwa-logo29"
file = "bonjwa/Bonjwa_Logo_29x29.png"
startx = 782
starty = 634
priority = 10

[[structure]]
name = "bonjwa-matteo-marius"
file = "bonjwa/Matteo-Marius-NeuerAlsNeu.png"
startx = 703
starty = 615
priority = 5

[[structure]]
name = "prinz"
file = "bonjwa/prinz3.png"
startx = 666
starty = 631
priority = 1

[[structure]]
name = "bonjwa-peepo2"
file = "bonjwa/peepo-1px-breiter.png"
startx = 688
starty = 632
priority = 1

[[structure]]
name = "kekluckeye"
file = "bonjwa/auge.png"
startx = 710
starty = 656
priority = 1

[[structure]]
name = "FlagArmenia"
file = "bonjwa/armenia_flag.png"
startx = 666
starty = 657
priority = 1

[[structure]]
name = "HeartArmenia"
file = "bonjwa/heart_bonjwa_armenia.png"
startx = 698
starty = 654
priority = 1

[[structure]]
name = "HeartUK"
file = "bonjwa/heartuk.png"
startx = 785
starty = 666
priority = 2

[[structure]]
name = "HeartArmeniaUK"
file = "bonjwa/heartarmeniauk.png"
startx = 688
starty = 666
priority = 2


[[structure]]
name = "frenchpress"
file = "bonjwa/frenchpress.png"
startx = 775
starty = 659
priority = 2

[[structure]]
name = "HeartDE"
file = "bonjwa/deheart.png"
startx = 820
starty = 634
priority = 2

[[structure]]
name = "touri"
file = "bonjwa/touri.png"
startx = 810
starty = 654
priority = 10

# [[structure]]
# name = "FroschHut"
# file = "bonjwa/frosch_hut.png"
# startx = 809
# starty = 144
# priority = 2

# endregion

# region left side

[[structure]]
name = "greenbg"
file = "bonjwa/greenbg.png"
startx = 188
starty = 633
priority = 2

[[structure]]
name = "rightuppercornergreenbg"
file = "bonjwa/greenbg_right_upper_corner.png"
startx = 253
starty = 633
priority = 2

[[structure]]
name = "helm"
file = "bonjwa/helm.png"
startx = 192
starty = 658
priority = 2

[[structure]]
name = "bonjwa-rad"
file = "bonjwa/BonjwaRad.png"
startx = 273
starty = 634
priority = 10

[[structure]]
name = "gans"
file = "bonjwa/Gans_gespiegelt.png"
startx = 213
starty = 631
priority = 3

[[structure]]
name = "fuchs"
file = "bonjwa/fuchs.png"
startx = 208
starty = 643
priority = 1

[[structure]]
name = "rb"
file = "bonjwa/rbbean.png"
startx = 222
starty = 633
priority = 3

[[structure]]
name = "phunk2"
file = "bonjwa/phunkmopsfrosch.png"
startx = 205
starty = 652
priority = 2

[[structure]]
name = "pyramid2"
file = "bonjwa/pyramidenhead.png"
startx = 193
starty = 633
priority = 3

[[structure]]
name = "items"
file = "bonjwa/items.png"
startx = 215
starty = 687
priority = 3

[[structure]]
name = "sukiandfriends-blumen"
file = "bonjwa/sukiandfiends_blumenDeko.png"
startx = 216
starty = 630
priority = 1

[[structure]]
name = "sukiandfriends"
file = "bonjwa/sukiandfriends.png"
startx = 216
starty = 630
priority = 2

[[structure]]
name = "leaf"
file = "bonjwa/acleaf.png"
startx = 269
starty = 632
priority = 2

[[structure]]
name = "schagges"
file = "bonjwa/schagges.png"
startx = 289
starty = 634
priority = 2

[[structure]]
name = "sukibird"
file = "bonjwa/bird.png"
startx = 243
starty = 697
priority = 2

[[structure]]
name = "cutebird"
file = "bonjwa/cutebird.png"
startx = 319
starty = 638
priority = 2

[[structure]]
name = "shushucat"
file = "bonjwa/shushucat.png"
startx = 276
starty = 728
priority = 2



# endregion

# region misc

[[structure]]
name = "free-iran-flagge"
file = "bonjwa/Free_Iran_Flagge.png"
startx = 1555
starty = 881
priority = 1

[[structure]]
name = "suun"
file = "bonjwa/suun2.png"
startx = 237
starty = 896
priority = 1

[[structure]]
name = "pietsmiet"
file = "bonjwa/pietsmiet.png"
startx = 1357
starty = 632
priority = 1

# endregion
